// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgkcxkcyvgvpvozgdnuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpna2N4a2N5dmd2cHZvemdkbnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTkyMDAsImV4cCI6MjA2MjY5NTIwMH0.FAXWfwb6GGaCIAfrUK5koO3qHFKXbhgApAN0A4K-E4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);